a=input("Digite algo aqui: ")
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumerico?', a.isalnum())
print(f'Está em maiúsculas? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está capitalizada? {a.istitle()}')
print(f'Tem decimais? {a.isdecimal()}')